version: '3'
services:
  keycloak_server:
    restart: always
    image: quay.io/keycloak/keycloak:23.0.4
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=keycloak_admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak_admin
