version: '3'
services:
  my_react_app:
    restart: always
    image: node:18
    working_dir: /app
    volumes:
      - ./my-react-app:/app
    ports:
      - 3018:3018
    command: /bin/bash -c "npm install && npm run dev"
  keycloak_server:
    restart: always
    image: quay.io/keycloak/keycloak:23.0.4
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=keycloak_admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak_admin
