version: '3'
services:
  sessions_sinatra:
    image: redis:7.0-alpine
    restart: always
  my_sinatra_app:
    restart: always
    image: ruby:3.0.4
    ports:
      - 3006:9292
    working_dir: /app
    volumes:
      - ./my-sinatra-app:/app
    command: /bin/bash -c "bundle install && bundle exec rackup --host 0.0.0.0"
  my_node_app:
    restart: always
    image: node:16
    working_dir: /app
    volumes:
      - ./my-node-app:/app
    ports:
      - 3000:3000
    command: /bin/bash -c "npm install && npm run start:authorization-code-flow"
  keycloak_server:
    restart: always
    image: quay.io/keycloak/keycloak:23.0.4
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=keycloak_admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak_admin
